using System;

namespace Melt
{
    public enum eTreasureType
    {
        none = 0,
        fishingLoot = 1,
        jewelry = 2
    }

    enum eSpellType
    {
        Undef_SpellType = 0,
        Enchantment_SpellType = 1,
        Projectile_SpellType = 2,
        Boost_SpellType = 3,
        Transfer_SpellType = 4,
        PortalLink_SpellType = 5,
        PortalRecall_SpellType = 6,
        PortalSummon_SpellType = 7,
        PortalSending_SpellType = 8,
        Dispel_SpellType = 9,
        LifeProjectile_SpellType = 10,
        FellowBoost_SpellType = 11,
        FellowEnchantment_SpellType = 12,
        FellowPortalSending_SpellType = 13,
        FellowDispel_SpellType = 14,
        EnchantmentProjectile_SpellType = 15,
        FORCE_SpellType_32_BIT = 0x7FFFFFFF,
    };

    [Flags]
    enum eSpellIndex
    {
        Undef_SpellIndex = 0x0,
        Resistable_SpellIndex = 0x1,
        PKSensitive_SpellIndex = 0x2,
        Beneficial_SpellIndex = 0x4,
        SelfTargeted_SpellIndex = 0x8,
        Reversed_SpellIndex = 0x10,
        NotIndoor_SpellIndex = 0x20,
        NotOutdoor_SpellIndex = 0x40,
        NotResearchable_SpellIndex = 0x80,
        Projectile_SpellIndex = 0x100,
        CreatureSpell_SpellIndex = 0x200,
        ExcludedFromItemDescriptions_SpellIndex = 0x400,
        IgnoresManaConversion_SpellIndex = 0x800,
        NonTrackingProjectile_SpellIndex = 0x1000,
        FellowshipSpell_SpellIndex = 0x2000,
        FastCast_SpellIndex = 0x4000,
        IndoorLongRange_SpellIndex = 0x8000,
        DamageOverTime_SpellIndex = 0x10000,
        FORCE_SpellIndex_32_BIT = 0x7FFFFFFF,
    };

    //low = T2
    //med = T3
    //high = T4
    public enum eTreasureGeneratorType
    {
        T1_NoobChest = 6,
        T1_ChestGreenmire1 = 92,
        T1_ChestGreenmire2 = 93,
        T1_ChestGreenmireGems = 18,
        T1_ChestColierMine = 313, //changed from 2
        T1_Chest = 4, //changed from 2
        T1_Money = 16, //changed from 2

        T2_Chest = 3, //changed from 3
        T2_Money = 15, //changed from 3

        T3_Chest = 1, //changed from 4
        T3_Money = 13, //changed from 4
        T3_ScrollSteelChest = 338, //changed from 4
        T3_MastersHolding = 340, //changed from 4

        T4_HeaRaiderCache = 365,
        T4_ReinforcedOakenChest = 422,
        T4_DirectivesCache = 339,//changed from 5

        T5_ReinforcedMahoganyChest = 421,
        T5_Chest_Aerlinthe = 317,
        T5_ChestFrore = 59,
        T5_AluvianCasinoChest = 349,
        T5_GharundimCasinoChest = 350,
        T5_ShoCasinoChest = 351,
        T5_SingularityTrove = 341,

        T1_RunedChest = 414,
        T2_RunedChest = 410,
        T3_RunedChest = 411,
        T4_RunedChest = 412,
        T5_RunedChest = 413,

        Tx_ChestTombLoot = 395, //unknown chest location and tier, not being used for now
        Tx_TreasureOfTheOrderAndSactumOfTheHopeslayerChest = 334,

        T1_General = 453,
        T1_Warrior = 459,
        T1_Magic = 465,

        T2_General = 457,
        T2_Warrior = 451,
        T2_Magic = 463,

        T3_General = 456,
        T3_Warrior = 450,
        T3_Magic = 462,

        T4_General = 454,
        T4_Warrior = 448,
        T4_Magic = 460,

        T5_General = 452,
        T5_Warrior = 458,
        T5_Magic = 464,

        T6_General = 449,
        T6_Warrior = 455,
        T6_Magic = 461,

        T1_CreatureLords = 24,
        T2_CreatureLords = 22,
        T4_CreatureLords = 21,
        T5_CreatureLords = 19,

        T2_Bosses = 28,
        T3_Bosses = 27,

        T4_BossesGeneral = 146,
        T4_BossesMagic = 25,

        T5_BossesGeneral = 29,
        T5_BossesMagic = 31,

        T6_BossesGeneral = 32,
        T6_BossesMagic = 26,

        T1_GolemKillTasks = 36,
        T2_GolemKillTasks = 34,
        T3_GolemKillTasks = 33,
        T4_GolemKillTasks = 35,

        T1_BanderlingCaptainAndRaider = 48,
        T1_DrudgeSlaves = 69,
        T1_HollowMinions = 72,
        T1_DrudgeProwler = 77,
        T1_DrudgeSkulker = 81,
        T1_DrudgeSneaker = 83,
        T1_IceGolem = 89,
        T1_Gromnie = 94,
        T1_AmplothRaider = 106,
        T1_BarkerMosswart = 123,
        T1_MosswartChief = 126,
        T1_CreeperMosswart = 127,
        T1_MosswartMucker = 132,
        T1_MosswartMucker2 = 134,
        T1_Mosswarts = 138,
        T1_MosswartShaman = 140,
        T1_InjuredOlthoi = 144,
        T1_RedPhyntosWasp = 153,
        T1_SwampRat = 164,
        T1_AsteSclavus = 166,
        T1_SmallShadowChild = 172,

        T2_HollowMinions = 86,
        T2_GraniteGolem = 88,
        T2_RankMoarsman = 115,
        T2_ShadowyWarrior = 154,
        T2_SilverRat = 161,

        T3_UnstableGlacialGolem = 90,
        T3_SableGromnie = 95,
        T3_FrostMattekar = 113,

        T5_ReedsharkSlasherAndBlackmireTempleBosses = 23,

        T6_OrphanageBosses = 20,
        T6_SmallGoldPlatGeliditeGolems = 87,
        T6_WhiteRabbit = 157,

        Tx_BabeTheBlueAuroch = 38,
        Tx_FullDeru = 62,
        Tx_GreenDeru = 63,
        Tx_OldDeru = 64,
        Tx_TallDeru = 65,
        Tx_StrawDrudge = 77,
        Tx_CandyStick = 91,
        Tx_MarriageQuestCreatures = 96,
        Tx_ColossalMonougaAndPaul = 116,
        Tx_GrievverSpawnAndMosswartKin = 142,
        Tx_OlthoiCrawler = 143,
        Tx_OlthoiGrubAndLarvae = 145,
        Tx_OlthoiGardenerHarvesterAndNymph = 147,
        Tx_OlthoiNobleQueenGardenerHarvester = 148,
        Tx_OlthoiQueen = 149,
        Tx_OlthoiSoldier = 150,
        Tx_OlthoiWorm = 151,
        Tx_StrawPhyntosWasp = 152,
        Tx_BossRabbitsAndSparringGolem = 156,
        Tx_StrawRat = 160,
        Tx_AlfregaTheReedshark = 164,
        Tx_SpireShadow = 171,
        Tx_SmallShadowSpireChild = 173,
        Tx_ShadowSpireChild = 174,
        Tx_SpireShadow2 = 176,
        Tx_AdminChest = 2,
    }

    //regular: 3 to 5 items
    //special: 5 to 15 items

    //t1: level 1-26
    //t2: level 27-62
    //t3: level 65-95
    //t4: level 95-110
    //t5: level 100-135
    //t6: level 135-161

    //public enum eTreasureGeneratorType
    //{
    //    none = 0,
    //    warriorAluvianHigh = 1,//warriorGharundimHigh, warriorHigh, warriorShoHigh
    //    warriorAluvianMed = 3,//warriorGharundimMed, warriorMed, warriorShoMed
    //    warriorAluvianLow = 4,//warriorGharundimLow, warriorLow, warriorShoLow
    //    glitterHigh = 13,//minerHigh, moneyHigh, thiefHigh
    //    glitterMed = 15,//minerMed, moneyMed, thiefMed
    //    glitterLow = 16,//minerLow, moneyLow, thiefLow
    //    generalHigh = 454, //foodHigh, healerHigh, utilityHigh
    //    generalMed = 456, //healerMed, utilityMed
    //    generalLow = 457, //foodLow, healerLow, utilityLow
    //    poor = 459,
    //    magicHigh = 460, //scholarHigh
    //    magicMed = 462,
    //    magicLow = 463,
    //}

    enum eHeritageGroups
    {
        none = 0,
        aluvian = 1,
        gharundim = 2,
        sho = 3,
        viamontian = 4,
        umbraenShadow = 5,
        gearKnight = 6,
        tumerok = 7,
        lugian = 8,
        empyrean = 9,
        penumbraenShadow = 10,
        undead = 11,
        olthoiSolder = 12,
        olthoiSpitter = 13
    }

    enum eElements
    {
        none = 0,
        slashing = 1,
        piercing = 2,
        bludgeoning = 3,
        cold = 4,
        fire = 5,
        acid = 6,
        lightning = 7
    }

    enum eWieldRequirements
    {
        undef = 0,
        skill = 1,
        baseSkill = 2,
        attribute = 3,
        baseAttribute = 4,
        vital = 5, //unconfirmed
        baseVital = 6,
        level = 7,
        skillAdvancementClass = 8,
        factionMember = 9
    }

    [Flags]
    enum eResistanceModifier
    {
        undef = 0,
        slashing = 1,
        piercing = 2,
        bludgeoning = 4,
        cold = 8,
        fire = 16,
        acid = 32,
        lightning = 64
    }

    [Flags]
    enum eAppraisalLongDescDecorations
    {
        prependWorkmanship = 0x1,
        prependMaterial = 0x2,
        appendGemInfo = 0x4,
    };

    public enum eMaterialType
    {
        ceramic = 1,
        porcelain = 2,
        cloth = 3,
        linen = 4,
        satin = 5,
        silk = 6,
        velvet = 7,
        wool = 8,
        gem = 9,
        agate = 10,
        amber = 11,
        amethyst = 12,
        aquamarine = 13,
        azurite = 14,
        blackGarnet = 15,
        blackOpal = 16,
        bloodstone = 17,
        carnelian = 18,
        citrine = 19,
        diamond = 20,
        emerald = 21,
        fireOpal = 22,
        greenGarnet = 23,
        greenJade = 24,
        hematite = 25,
        imperialTopaz = 26,
        jet = 27,
        lapisLazuli = 28,
        lavenderJade = 29,
        malachite = 30,
        moonstone = 31,
        onyx = 32,
        opal = 33,
        peridot = 34,
        redGarnet = 35,
        RedJade = 36,
        roseQuartz = 37,
        ruby = 38,
        sapphire = 39,
        smokeyQuartz = 40,
        sunstone = 41,
        tigerEye = 42,
        tourmaline = 43,
        turquoise = 44,
        whiteJade = 45,
        whiteQuartz = 46,
        whiteSapphire = 47,
        yellowGarnet = 48,
        yellowTopaz = 49,
        zircon = 50,
        ivory = 51,
        leather = 52,
        armoredilloHide = 53,
        gromnieHide = 54,
        reedSharkHide = 55,
        metal = 56,
        brass = 57,
        bronze = 58,
        copper = 59,
        gold = 60,
        iron = 61,
        pyreal = 62,
        silver = 63,
        steel = 64,
        stone = 65,
        alabaster = 66,
        granite = 67,
        marble = 68,
        obsidian = 69,
        sandstone = 70,
        serpentine = 71,
        wood = 72,
        ebony = 73,
        mahogany = 74,
        oak = 75,
        pine = 76,
        teak = 77
    }

    [Flags]
    enum ePortalBitmask
    {
        undef = 0,
        none = 1,
        noPK = 2,
        noPKL = 4,
        noNPK = 8,
        noSummon = 16,
        noRecallOrTie = 32
    }

    enum eTolerance
    {
        undef = 0,
        stationary = 1,
        attackOnExamine = 2,
        neverAttack = 40,
        attackIfAttacked = 64
    }

    [Flags]
    enum eUIEffectType
    {
        UI_Effect_Undef = 0x0,
        UI_Effect_Magical = 0x1,
        UI_Effect_Poisoned = 0x2,
        UI_Effect_Boost_Health = 0x4,
        UI_Effect_Boost_Mana = 0x8,
        UI_Effect_Boost_Stamina = 0x10,
        UI_Effect_Fire = 0x20,
        UI_Effect_Lightning = 0x40,
        UI_Effect_Frost = 0x80,
        UI_Effect_Acid = 0x100,
        UI_Effect_Bludgeoning = 0x200,
        UI_Effect_Slashing = 0x400,
        UI_Effect_Piercing = 0x800,
        UI_Effect_Nether = 0x1000,
        FORCE_UI_Effect_Type_32_Bit = 0x7fffffff,
    };

    [Flags]
    enum ePKStatus
    {
        Undef_PKStatus = 0x0,
        Protected_PKStatus = 0x1,
        NPK_PKStatus = 0x2,
        PK_PKStatus = 0x4,
        Unprotected_PKStatus = 0x8,
        RubberGlue_PKStatus = 0x10,
        Free_PKStatus = 0x20,
        PKLite_PKStatus = 0x40,
        Creature_PKStatus = 0x8,
        Trap_PKStatus = 0x8,
        NPC_PKStatus = 0x1,
        Vendor_PKStatus = 0x10,
        Baelzharon_PKStatus = 0x20,
        FORCE_PKStatusEnum_32_BIT = 0x7FFFFFFF,
    };

    public enum eCreatureType
    {
        none = 0,
        olthoi = 1,
        banderling = 2,
        drudge = 3,
        mosswart = 4,
        lugian = 5,
        tumerok = 6,
        mite = 7,
        tusker = 8,
        phyntosWasp = 9,
        rat = 10,
        auroch = 11,
        cow = 12,
        golem = 13,
        undead = 14,
        gromnie = 15,
        reedshark = 16,
        armoredillo = 17,
        fae = 18,
        virindi = 19,
        wisp = 20,
        knathtaed = 21,
        shadow = 22,
        mattekar = 23,
        mumiyah = 24,
        rabbit = 25,
        sclavus = 26,
        shallowsShark = 27,
        monouga = 28,
        zefir = 29,
        skeleton = 30,
        human = 31,
        shreth = 32,
        chittick = 33,
        moarsman = 34,
        slithis = 36,
        fireElemental = 38,
        snowman = 39,
        bunny = 41,
        lightningElemental = 42,
        grievver = 44,
        niffis = 45,
        ursuin = 46,
        crystal = 47,
        hollowMinion = 48,
        scarecrow = 49,
        idol = 50,
        empyrean = 51,
        hopeslayer = 52,
        doll = 53,
        marionette = 54,
        carenzi = 55,
        siraluun = 56,
        aunTumerok = 57,
        heaTumerok = 58,
        simulacrum = 59,
        acidElemental = 60,
        frostElemental = 61,
        elemental = 62,
        statue = 63,
        wall = 64,
        alteredHuman = 65,
        device = 66,
        harbinger = 67,
        darkSarcophagus = 68,
        chicken = 69,
        gotrokLugian = 70,
        margul = 71,
        bleachedRabbit = 72,
        nastyRabbit = 73,
        grimacingRabbit = 74,
        burun = 75,
        target = 76,
        ghost = 77,
        fiun = 78,
        eater = 79,
        penguin = 80,
        ruschk = 81,
        thrungus = 82,
        viamontianKnight = 83,
        remoran = 84,
        swarm = 85,
        moar = 86,
        enchantedArms = 87,
        sleech = 88,
        mukkir = 89,
        merwart = 90,
        food = 91,
        paradoxOlthoi = 92,
        energy = 94,
        apparition = 95,
        aerbax = 96,
        touched = 97,
        blightedMoarsman = 98,
        gearKnight = 99,
        gurog = 100,
        anekshay = 101
    }

    enum eGeneratorType
    {
        Undef_GeneratorType = 0x0,
        Relative_GeneratorType = 0x1,
        Absolute_GeneratorType = 0x2,
        FORCE_GeneratorType_32_BIT = 0x7FFFFFFF,
    };

    enum eGeneratorTimeType
    {
        Undef_GeneratorTimeType = 0x0,
        RealTime_GeneratorTimeType = 0x1,
        Defined_GeneratorTimeType = 0x2,
        Event_GeneratorTimeType = 0x3,
        Night_GeneratorTimeType = 0x4,
        Day_GeneratorTimeType = 0x5,
        FORCE_GeneratorTimeType_32_BIT = 0x7FFFFFFF,
    };

    enum eGeneratorDestructionType
    {
        Undef_GeneratorDestruct = 0x0,
        Nothing_GeneratorDestruct = 0x1,
        Destroy_GeneratorDestruct = 0x2,
        Kill_GeneratorDestruct = 0x3,
        FORCE_GeneratorDestruct_32_BIT = 0x7FFFFFFF,
    };

    [Flags]
    enum eHookType
    {
        Undef_HookTypeEnum = 0x0,
        Floor_HookTypeEnum = 0x1,
        Wall_HookTypeEnum = 0x2,
        Ceiling_HookTypeEnum = 0x4,
        Yard_HookTypeEnum = 0x8,
        Roof_HookTypeEnum = 0x10,
        FORCE_HookTypeEnum_32_BIT = 0x7FFFFFFF,
    };

    enum eAttunedStatus
    {
        Normal_AttunedStatus = 0x0,
        Attuned_AttunedStatus = 0x1,
        Sticky_AttunedStatus = 0x2,
        FORCE_AttunedStatusEnum_32_BIT = 0x7FFFFFFF,
    };

    enum eBondedStatus : uint
    {
        Destroy_BondedStatus = 0xFFFFFFFE,
        Slippery_BondedStatus = 0xFFFFFFFF,
        Normal_BondedStatus = 0x0,
        Bonded_BondedStatus = 0x1,
        Sticky_BondedStatus = 0x2,
        FORCE_BondedStatusEnum_32_BIT = 0x7FFFFFFF,
    };

    enum eWeaponType
    {
        Undef_WeaponType = 0x0,
        Unarmed_WeaponType = 0x1,
        Sword_WeaponType = 0x2,
        Axe_WeaponType = 0x3,
        Mace_WeaponType = 0x4,
        Spear_WeaponType = 0x5,
        Dagger_WeaponType = 0x6,
        Staff_WeaponType = 0x7,
        Bow_WeaponType = 0x8,
        Crossbow_WeaponType = 0x9,
        Thrown_WeaponType = 0xA,
        TwoHanded_WeaponType = 0xB,
        Magic_WeaponType = 0xC,
    };

    enum eAttackHeight
    {
        Undef_Attack_Height = 0x0,
        High_Attack_Height = 0x1,
        Medium_Attack_Height = 0x2,
        Low_Attack_Height = 0x3,
        Num_Attack_Heights = 0x4,
        Force_Attack_Height_32_Bit = 0x7fffffff,
    };

    public enum eBodyHeight
    {
        Undef_Body_Height = 0x0,
        High_Body_Height = 0x1,
        Medium_Body_Height = 0x2,
        Low_Body_Height = 0x3,
        Num_Body_Heights = 0x4,
        Force_Body_Height32_Bit = 0x7fffffff,
    };

    [Flags]
    public enum eImbuedEffectType: uint
    {
        none = 0x0,
        criticalStrike = 0x1,
        cripplingBlow = 0x2,
        armorRending = 0x4,
        slashRending = 0x8,
        pierceRending = 0x10,
        bludgeonRending = 0x20,
        acidRending = 0x40,
        coldRending = 0x80,
        electricRending = 0x100,
        fireRending = 0x200,
        meleeDefense = 0x400,
        missileDefense = 0x800,
        magicDefense = 0x1000,
        spellbook = 0x2000,
        netherRending = 0x4000,
        ignoreSomeMagicProjectileDamage = 0x20000000,
        alwaysCritical = 0x40000000,
        ignoreAllArmor = 0x80000000
    };

    [Flags]
    enum eAttackType
    {
        Undef_AttackType = 0x0,
        Punch_AttackType = 0x1,
        Thrust_AttackType = 0x2,
        Slash_AttackType = 0x4,
        Kick_AttackType = 0x8,
        OffhandPunch_AttackType = 0x10,
        DoubleSlash_AttackType = 0x20,
        TripleSlash_AttackType = 0x40,
        DoubleThrust_AttackType = 0x80,
        TripleThrust_AttackType = 0x100,
        OffhandThrust_AttackType = 0x200,
        OffhandSlash_AttackType = 0x400,
        OffhandDoubleSlash_AttackType = 0x800,
        OffhandTripleSlash_AttackType = 0x1000,
        OffhandDoubleThrust_AttackType = 0x2000,
        OffhandTripleThrust_AttackType = 0x4000,
        Unarmed_AttackType = 0x19,
        MultiStrike_AttackType = 0x79E0,
        FORCE_AttackType_32_BIT = 0x7FFFFFFF,
    };

    [Flags]
    enum eCombatStyle
    {
        Undef_Combatstyle = 0x0,
        Unarmed_Combatstyle = 0x1,
        Onehanded_Combatstyle = 0x2,
        Onehandedandshield_Combatstyle = 0x4,
        Twohanded_Combatstyle = 0x8,
        Bow_Combatstyle = 0x10,
        Crossbow_Combatstyle = 0x20,
        Sling_Combatstyle = 0x40,
        Thrownweapon_Combatstyle = 0x80,
        Dualwield_Combatstyle = 0x100,
        Magic_Combatstyle = 0x200,
        Atlatl_Combatstyle = 0x400,
        Thrownshield_Combatstyle = 0x800,
        Reserved1_Combatstyle = 0x1000,
        Reserved2_Combatstyle = 0x2000,
        Reserved3_Combatstyle = 0x4000,
        Reserved4_Combatstyle = 0x8000,
        Stubbornmagic_Combatstyle = 0x10000,
        Stubbornprojectile_Combatstyle = 0x20000,
        Stubbornmelee_Combatstyle = 0x40000,
        Stubbornmissile_Combatstyle = 0x80000,
        Melee_Combatstyles = 0x10f,
        Missile_Combatstyles = 0xcf0,
        Magic_Combatstyles = 0x200,
        All_Combatstyle = 0xffff,
        FORCE_Combatstyle_32_Bit = 0x7fffffff,
    };

    public enum eItemUseable : uint
    {
        Useable_Undef = 0x0,
        Useable_No = 0x1,
        Useable_Self = 0x2,
        Useable_Wielded = 0x4,
        Useable_Contained = 0x8,
        Useable_Viewed = 0x10,
        Useable_Remote = 0x20,
        Useable_Never_Walk = 0x40,
        Useable_Objself = 0x80,
        Useable_Contained_Viewed = 0x18,
        Useable_Contained_Viewed_Remote = 0x38,
        Useable_Contained_Viewed_Remote_Never_Walk = 0x78,
        Useable_Viewed_Remote = 0x30,
        Useable_Viewed_Remote_Never_Walk = 0x70,
        Useable_Remote_Never_Walk = 0x60,
        Useable_Source_Wielded_Target_Wielded = 0x40004,
        Useable_Source_Wielded_Target_Contained = 0x80004,
        Useable_Source_Wielded_Target_Viewed = 0x100004,
        Useable_Source_Wielded_Target_Remote = 0x200004,
        Useable_Source_Wielded_Target_Remote_Never_Walk = 0x600004,
        Useable_Source_Contained_Target_Wielded = 0x40008,
        Useable_Source_Contained_Target_Contained = 0x80008,
        Useable_Source_Contained_Target_Objself_Or_Contained = 0x880008,
        Useable_Source_Contained_Target_Self_Or_Contained = 0xa0008,
        Useable_Source_Contained_Target_Viewed = 0x100008,
        Useable_Source_Contained_Target_Remote = 0x200008,
        Useable_Source_Contained_Target_Remote_Never_Walk = 0x600008,
        Useable_Source_Contained_Target_Remote_Or_Self = 0x220008,
        Useable_Source_Viewed_Target_Wielded = 0x40010,
        Useable_Source_Viewed_Target_Contained = 0x80010,
        Useable_Source_Viewed_Target_Viewed = 0x100010,
        Useable_Source_Viewed_Target_Remote = 0x200010,
        Useable_Source_Remote_Target_Wielded = 0x40020,
        Useable_Source_Remote_Target_Contained = 0x80020,
        Useable_Source_Remote_Target_Viewed = 0x100020,
        Useable_Source_Remote_Target_Remote = 0x200020,
        Useable_Source_Remote_Target_Remote_Never_Walk = 0x600020,
        Useable_Source_Mask = 0xffff,
        Useable_Target_Mask = 0xffff0000,
        FORCE_Item_Useable_32_Bit = 0x7fffffff,
    }

    enum eCombatMode
    {
        Undef_Combat_Mode = 0x0,
        Noncombat_Combat_Mode = 0x1,
        Melee_Combat_Mode = 0x2,
        Missile_Combat_Mode = 0x4,
        Magic_Combat_Mode = 0x8,
        Valid_Combat_Modes = 0xf,
        Combat_Combat_Mode = 0xe,
        FORCE_Combat_Mode_32_Bit = 0x7fffffff,
    };

    [Flags]
    public enum eDamageType
    {
        Undef_Damage_Type = 0x0,
        Slash_Damage_Type = 0x1,
        Pierce_Damage_Type = 0x2,
        Bludgeon_Damage_Type = 0x4,
        Cold_Damage_Type = 0x8,
        Fire_Damage_Type = 0x10,
        Acid_Damage_Type = 0x20,
        Electric_Damage_Type = 0x40,
        Health_Damage_Type = 0x80,
        Stamina_Damage_Type = 0x100,
        Mana_Damage_Type = 0x200,
        Nether_Damage_Type = 0x400,
        Base_Damage_Type = 0x10000000,
        FORCE_Damage_Type_32_Bit = 0x7fffffff,
    };

    [Flags]
    enum eInventoryLocations
    {
        None_Loc = 0x0,
        Head_Wear_Loc = 0x1,
        Chest_Wear_Loc = 0x2,
        Abdomen_Wear_Loc = 0x4,
        Upper_Arm_Wear_Loc = 0x8,
        Lower_Arm_Wear_Loc = 0x10,
        Hand_Wear_Loc = 0x20,
        Upper_Leg_Wear_Loc = 0x40,
        Lower_Leg_Wear_Loc = 0x80,
        Foot_Wear_Loc = 0x100,
        Chest_Armor_Loc = 0x200,
        Abdomen_Armor_Loc = 0x400,
        Upper_Arm_Armor_Loc = 0x800,
        Lower_Arm_Armor_Loc = 0x1000,
        Upper_Leg_Armor_Loc = 0x2000,
        Lower_Leg_Armor_Loc = 0x4000,
        Neck_Wear_Loc = 0x8000,
        Wrist_Wear_Left_Loc = 0x10000,
        Wrist_Wear_Right_Loc = 0x20000,
        Finger_Wear_Left_Loc = 0x40000,
        Finger_Wear_Right_Loc = 0x80000,
        Melee_Weapon_Loc = 0x100000,
        Shield_Loc = 0x200000,
        Missile_Weapon_Loc = 0x400000,
        Missile_Ammo_Loc = 0x800000,
        Held_Loc = 0x1000000,
        Two_Handed_Loc = 0x2000000,
        Trinket_One_Loc = 0x4000000,
        Cloak_Loc = 0x8000000,
        Sigil_One_Loc = 0x10000000,
        Sigil_Two_Loc = 0x20000000,
        Sigil_Three_Loc = 0x40000000,
        Clothing_Loc = 0x80001ff,
        Armor_Loc = 0x7e00,
        Jewelry_Loc = 0x7c0f8000,
        Wrist_Wear_Loc = 0x30000,
        Finger_Wear_Loc = 0xc0000,
        Sigil_Loc = 0x70000000,
        Ready_Slot_Loc = 0x3f00000,
        Weapon_Loc = 0x2500000,
        Weapon_Ready_Slot_Loc = 0x3500000,
        All_Loc = 0x7fffffff,
        Can_Go_In_Ready_Slot_Loc = 0x7fffffff,
        FORCE_Inventory_Loc_32_Bit = 0x7fffffff,
    };

    [Flags]
    enum ePhysicsState
    {
        Static_PS = 0x1,
        Unused1_PS = 0x2,
        Ethereal_PS = 0x4,
        Report_Collisions_PS = 0x8,
        Ignore_Collisions_PS = 0x10,
        Nodraw_PS = 0x20,
        Missile_PS = 0x40,
        Pushable_PS = 0x80,
        Alignpath_PS = 0x100,
        Pathclipped_PS = 0x200,
        Gravity_PS = 0x400,
        Lighting_On_PS = 0x800,
        Particle_Emitter_PS = 0x1000,
        Unnused2_PS = 0x2000,
        Hidden_PS = 0x4000,
        Scripted_Collision_PS = 0x8000,
        Has_Physics_Bsp_PS = 0x10000,
        Inelastic_PS = 0x20000,
        Has_Default_Anim_PS = 0x40000,
        Has_Default_Script_PS = 0x80000,
        Cloaked_PS = 0x100000,
        Report_Collisions_As_Environment_PS = 0x200000,
        Edge_Slide_PS = 0x400000,
        Sledding_PS = 0x800000,
        Frozen_PS = 0x1000000,
        FORCE_PhysicsState_32_BIT = 0x7FFFFFFF,
    };

    public enum eRegenerationType
    {
        Undef_RegenerationType = 0x0,
        Destruction_RegenerationType = 0x1,
        PickUp_RegenerationType = 0x2,
        Death_RegenerationType = 0x4,
        FORCE_RegenerationType_32_BIT = 0x7FFFFFFF,
    };

    public enum eRegenLocationType
    {
        Undef_RegenLocationType = 0x0,
        OnTop_RegenLocationType = 0x1,
        Scatter_RegenLocationType = 0x2,
        Specific_RegenLocationType = 0x4,
        Contain_RegenLocationType = 0x8,
        Wield_RegenLocationType = 0x10,
        Shop_RegenLocationType = 0x20,
        Checkpoint_RegenLocationType = 0x38,
        Treasure_RegenLocationType = 0x40,
        OnTopTreasure_RegenLocationType = 0x41,
        ScatterTreasure_RegenLocationType = 0x42,
        SpecificTreasure_RegenLocationType = 0x44,
        ContainTreasure_RegenLocationType = 0x48,
        WieldTreasure_RegenLocationType = 0x50,
        ShopTreasure_RegenLocationType = 0x60,
        FORCE_RegenLocationType_32_BIT = 0x7FFFFFFF,
    };

    public enum eDestinationType
    {
        Undef_DestinationType = 0x0,
        Contain_DestinationType = 0x1,
        Wield_DestinationType = 0x2,
        Shop_DestinationType = 0x4,
        Treasure_DestinationType = 0x8,
        HouseBuy_DestinationType = 0x10,
        HouseRent_DestinationType = 0x20,
        Checkpoint_DestinationType = 0x7,
        ContainTreasure_DestinationType = 0x9,
        WieldTreasure_DestinationType = 0xA,
        ShopTreasure_DestinationType = 0xC,
        FORCE_DestinationType_32_BIT = 0x7FFFFFFF,
    };

    [Flags]
    public enum eItemType : uint
    {
        Type_Undef = 0x0,
        Type_Melee_Weapon = 0x1,
        Type_Armor = 0x2,
        Type_Clothing = 0x4,
        Type_Jewelry = 0x8,
        Type_Creature = 0x10,
        Type_Food = 0x20,
        Type_Money = 0x40,
        Type_Misc = 0x80,
        Type_Missile_Weapon = 0x100,
        Type_Container = 0x200,
        Type_Useless = 0x400,
        Type_Gem = 0x800,
        Type_Spell_Components = 0x1000,
        Type_Writable = 0x2000,
        Type_Key = 0x4000,
        Type_Caster = 0x8000,
        Type_Portal = 0x10000,
        Type_Lockable = 0x20000,
        Type_Promissory_Note = 0x40000,
        Type_Manastone = 0x80000,
        Type_Service = 0x100000,
        Type_Magic_Wieldable = 0x200000,
        Type_Craft_Cooking_Base = 0x400000,
        Type_Craft_Alchemy_Base = 0x800000,
        Type_Craft_Fletching_Base = 0x1000000,
        Type_Craft_Alchemy_Intermediate = 0x4000000,
        Type_Craft_Fletching_Intermediate = 0x8000000,
        Type_Lifestone = 0x10000000,
        Type_Tinkering_Tool = 0x20000000,
        Type_Tinkering_Material = 0x40000000,
        Type_Gameboard = 0x80000000,
        Type_Portal_Magic_Target = 0x10010000,
        Type_Lockable_Magic_Target = 0x280,
        Type_Vestements = 0x6,
        Type_Weapon = 0x101,
        Type_Weapon_Or_Caster = 0x8101,
        Type_Item = 0x2dfbef,
        Type_Redirectable_Item_Enchantment_Target = 0x8107,
        Type_Item_Enchantable_Target = 0x88b8f,
        Type_Vendor_Shopkeep = 0x480467a7,
        Type_Vendor_Grocer = 0x446220,
        FORCE_Item_Type_32_Bit = 0x7fffffff,
    };

    public enum eAmmoType
    {
        Ammo_None = 0x0,
        Ammo_Arrow = 0x1,
        Ammo_Bolt = 0x2,
        Ammo_Atlatl = 0x4,
        Ammo_Arrow_Crystal = 0x8,
        Ammo_Bolt_Crystal = 0x10,
        Ammo_Atlatl_Crystal = 0x20,
        Ammo_Arrow_Chorizite = 0x40,
        Ammo_Bolt_Chorizite = 0x80,
        Ammo_Atlatl_Chorizite = 0x100,
        FORCE_Ammo_Type_32_Bit = 0x7fffffff,
    };

    public enum eCombatUse
    {
        Combat_Use_None = 0x0,
        Combat_Use_Melee = 0x1,
        Combat_Use_Missile = 0x2,
        Combat_Use_Ammo = 0x3,
        Combat_Use_Shield = 0x4,
        Combat_Use_Two_Handed = 0x5,
        FORCE_Combat_Use_32_Bit = 0x7fffffff,
    };

    public enum eRadarEnum
    {
        Undef_RadarEnum = 0x0,
        ShowNever_RadarEnum = 0x1,
        ShowMovement_RadarEnum = 0x2,
        ShowAttacking_RadarEnum = 0x3,
        ShowAlways_RadarEnum = 0x4,
        FORCE_RadarEnum_32_BIT = 0x7FFFFFFF,
    };

    enum eRadarBlipShape
    {
        Undef_RadarBlipShape = 0x0,
        Circle_RadarBlipShape = 0x1,
        Box_RadarBlipShape = 0x2,
        X_RadarBlipShape = 0x3,
        Plus_RadarBlipShape = 0x4,
        Triangle_RadarBlipShape = 0x5,
        InvertedTriangle_RadarBlipShape = 0x6,
        XBox_RadarBlipShape = 0x7,
        Default_RadarBlipShape = 0x4,
        AllegianceMember_RadarBlipShape = 0x2,
        FellowshipLeader_RadarBlipShape = 0x5,
        Fellowship_RadarBlipShape = 0x6,
        Threat_RadarBlipShape = 0x3,
        ThreatAllegiance_RadarBlipShape = 0x7,
    };

    public enum eSoundType
    {
        Sound_Invalid = 0x0,
        Sound_Speak1 = 0x1,
        Sound_Random = 0x2,
        Sound_Attack1 = 0x3,
        Sound_Attack2 = 0x4,
        Sound_Attack3 = 0x5,
        Sound_SpecialAttack1 = 0x6,
        Sound_SpecialAttack2 = 0x7,
        Sound_SpecialAttack3 = 0x8,
        Sound_Damage1 = 0x9,
        Sound_Damage2 = 0xA,
        Sound_Damage3 = 0xB,
        Sound_Wound1 = 0xC,
        Sound_Wound2 = 0xD,
        Sound_Wound3 = 0xE,
        Sound_Death1 = 0xF,
        Sound_Death2 = 0x10,
        Sound_Death3 = 0x11,
        Sound_Grunt1 = 0x12,
        Sound_Grunt2 = 0x13,
        Sound_Grunt3 = 0x14,
        Sound_Oh1 = 0x15,
        Sound_Oh2 = 0x16,
        Sound_Oh3 = 0x17,
        Sound_Heave1 = 0x18,
        Sound_Heave2 = 0x19,
        Sound_Heave3 = 0x1A,
        Sound_Knockdown1 = 0x1B,
        Sound_Knockdown2 = 0x1C,
        Sound_Knockdown3 = 0x1D,
        Sound_Swoosh1 = 0x1E,
        Sound_Swoosh2 = 0x1F,
        Sound_Swoosh3 = 0x20,
        Sound_Thump1 = 0x21,
        Sound_Smash1 = 0x22,
        Sound_Scratch1 = 0x23,
        Sound_Spear = 0x24,
        Sound_Sling = 0x25,
        Sound_Dagger = 0x26,
        Sound_ArrowWhiz1 = 0x27,
        Sound_ArrowWhiz2 = 0x28,
        Sound_CrossbowPull = 0x29,
        Sound_CrossbowRelease = 0x2A,
        Sound_BowPull = 0x2B,
        Sound_BowRelease = 0x2C,
        Sound_ThrownWeaponRelease1 = 0x2D,
        Sound_ArrowLand = 0x2E,
        Sound_Collision = 0x2F,
        Sound_HitFlesh1 = 0x30,
        Sound_HitLeather1 = 0x31,
        Sound_HitChain1 = 0x32,
        Sound_HitPlate1 = 0x33,
        Sound_HitMissile1 = 0x34,
        Sound_HitMissile2 = 0x35,
        Sound_HitMissile3 = 0x36,
        Sound_Footstep1 = 0x37,
        Sound_Footstep2 = 0x38,
        Sound_Walk1 = 0x39,
        Sound_Dance1 = 0x3A,
        Sound_Dance2 = 0x3B,
        Sound_Dance3 = 0x3C,
        Sound_Hidden1 = 0x3D,
        Sound_Hidden2 = 0x3E,
        Sound_Hidden3 = 0x3F,
        Sound_Eat1 = 0x40,
        Sound_Drink1 = 0x41,
        Sound_Open = 0x42,
        Sound_Close = 0x43,
        Sound_OpenSlam = 0x44,
        Sound_CloseSlam = 0x45,
        Sound_Ambient1 = 0x46,
        Sound_Ambient2 = 0x47,
        Sound_Ambient3 = 0x48,
        Sound_Ambient4 = 0x49,
        Sound_Ambient5 = 0x4A,
        Sound_Ambient6 = 0x4B,
        Sound_Ambient7 = 0x4C,
        Sound_Ambient8 = 0x4D,
        Sound_Waterfall = 0x4E,
        Sound_LogOut = 0x4F,
        Sound_LogIn = 0x50,
        Sound_LifestoneOn = 0x51,
        Sound_AttribUp = 0x52,
        Sound_AttribDown = 0x53,
        Sound_SkillUp = 0x54,
        Sound_SkillDown = 0x55,
        Sound_HealthUp = 0x56,
        Sound_HealthDown = 0x57,
        Sound_ShieldUp = 0x58,
        Sound_ShieldDown = 0x59,
        Sound_EnchantUp = 0x5A,
        Sound_EnchantDown = 0x5B,
        Sound_VisionUp = 0x5C,
        Sound_VisionDown = 0x5D,
        Sound_Fizzle = 0x5E,
        Sound_Launch = 0x5F,
        Sound_Explode = 0x60,
        Sound_TransUp = 0x61,
        Sound_TransDown = 0x62,
        Sound_BreatheFlaem = 0x63,
        Sound_BreatheAcid = 0x64,
        Sound_BreatheFrost = 0x65,
        Sound_BreatheLightning = 0x66,
        Sound_Create = 0x67,
        Sound_Destroy = 0x68,
        Sound_Lockpicking = 0x69,
        Sound_UI_EnterPortal = 0x6A,
        Sound_UI_ExitPortal = 0x6B,
        Sound_UI_GeneralQuery = 0x6C,
        Sound_UI_GeneralError = 0x6D,
        Sound_UI_TransientMessage = 0x6E,
        Sound_UI_IconPickUp = 0x6F,
        Sound_UI_IconSuccessfulDrop = 0x70,
        Sound_UI_IconInvalid_Drop = 0x71,
        Sound_UI_ButtonPress = 0x72,
        Sound_UI_GrabSlider = 0x73,
        Sound_UI_ReleaseSlider = 0x74,
        Sound_UI_NewTargetSelected = 0x75,
        Sound_UI_Roar = 0x76,
        Sound_UI_Bell = 0x77,
        Sound_UI_Chant1 = 0x78,
        Sound_UI_Chant2 = 0x79,
        Sound_UI_DarkWhispers1 = 0x7A,
        Sound_UI_DarkWhispers2 = 0x7B,
        Sound_UI_DarkLaugh = 0x7C,
        Sound_UI_DarkWind = 0x7D,
        Sound_UI_DarkSpeech = 0x7E,
        Sound_UI_Drums = 0x7F,
        Sound_UI_GhostSpeak = 0x80,
        Sound_UI_Breathing = 0x81,
        Sound_UI_Howl = 0x82,
        Sound_UI_LostSouls = 0x83,
        Sound_UI_Squeal = 0x84,
        Sound_UI_Thunder1 = 0x85,
        Sound_UI_Thunder2 = 0x86,
        Sound_UI_Thunder3 = 0x87,
        Sound_UI_Thunder4 = 0x88,
        Sound_UI_Thunder5 = 0x89,
        Sound_UI_Thunder6 = 0x8A,
        Sound_RaiseTrait = 0x8B,
        Sound_WieldObject = 0x8C,
        Sound_UnwieldObject = 0x8D,
        Sound_ReceiveItem = 0x8E,
        Sound_PickUpItem = 0x8F,
        Sound_DropItem = 0x90,
        Sound_ResistSpell = 0x91,
        Sound_PicklockFail = 0x92,
        Sound_LockSuccess = 0x93,
        Sound_OpenFailDueToLock = 0x94,
        Sound_TriggerActivated = 0x95,
        Sound_SpellExpire = 0x96,
        Sound_ItemManaDepleted = 0x97,
        Sound_TriggerActivated1 = 0x98,
        Sound_TriggerActivated2 = 0x99,
        Sound_TriggerActivated3 = 0x9A,
        Sound_TriggerActivated4 = 0x9B,
        Sound_TriggerActivated5 = 0x9C,
        Sound_TriggerActivated6 = 0x9D,
        Sound_TriggerActivated7 = 0x9E,
        Sound_TriggerActivated8 = 0x9F,
        Sound_TriggerActivated9 = 0xA0,
        Sound_TriggerActivated10 = 0xA1,
        Sound_TriggerActivated11 = 0xA2,
        Sound_TriggerActivated12 = 0xA3,
        Sound_TriggerActivated13 = 0xA4,
        Sound_TriggerActivated14 = 0xA5,
        Sound_TriggerActivated15 = 0xA6,
        Sound_TriggerActivated16 = 0xA7,
        Sound_TriggerActivated17 = 0xA8,
        Sound_TriggerActivated18 = 0xA9,
        Sound_TriggerActivated19 = 0xAA,
        Sound_TriggerActivated20 = 0xAB,
        Sound_TriggerActivated21 = 0xAC,
        Sound_TriggerActivated22 = 0xAD,
        Sound_TriggerActivated23 = 0xAE,
        Sound_TriggerActivated24 = 0xAF,
        Sound_TriggerActivated25 = 0xB0,
        Sound_TriggerActivated26 = 0xB1,
        Sound_TriggerActivated27 = 0xB2,
        Sound_TriggerActivated28 = 0xB3,
        Sound_TriggerActivated29 = 0xB4,
        Sound_TriggerActivated30 = 0xB5,
        Sound_TriggerActivated31 = 0xB6,
        Sound_TriggerActivated32 = 0xB7,
        Sound_TriggerActivated33 = 0xB8,
        Sound_TriggerActivated34 = 0xB9,
        Sound_TriggerActivated35 = 0xBA,
        Sound_TriggerActivated36 = 0xBB,
        Sound_TriggerActivated37 = 0xBC,
        Sound_TriggerActivated38 = 0xBD,
        Sound_TriggerActivated39 = 0xBE,
        Sound_TriggerActivated40 = 0xBF,
        Sound_TriggerActivated41 = 0xC0,
        Sound_TriggerActivated42 = 0xC1,
        Sound_TriggerActivated43 = 0xC2,
        Sound_TriggerActivated44 = 0xC3,
        Sound_TriggerActivated45 = 0xC4,
        Sound_TriggerActivated46 = 0xC5,
        Sound_TriggerActivated47 = 0xC6,
        Sound_TriggerActivated48 = 0xC7,
        Sound_TriggerActivated49 = 0xC8,
        Sound_TriggerActivated50 = 0xC9,
        Sound_HealthDownVoid = 0xCA,
        Sound_RegenDownVoid = 0xCB,
        Sound_SkillDownVoid = 0xCC,
        NUM_SOUND_TYPES = 0xCD,
        FORCE_SoundType_32_BIT = 0x7FFFFFFF,
    };

    public enum ePScriptType
    {
        PS_Invalid = 0x0,
        PS_Test1 = 0x1,
        PS_Test2 = 0x2,
        PS_Test3 = 0x3,
        PS_Launch = 0x4,
        PS_Explode = 0x5,
        PS_AttribUpRed = 0x6,
        PS_AttribDownRed = 0x7,
        PS_AttribUpOrange = 0x8,
        PS_AttribDownOrange = 0x9,
        PS_AttribUpYellow = 0xA,
        PS_AttribDownYellow = 0xB,
        PS_AttribUpGreen = 0xC,
        PS_AttribDownGreen = 0xD,
        PS_AttribUpBlue = 0xE,
        PS_AttribDownBlue = 0xF,
        PS_AttribUpPurple = 0x10,
        PS_AttribDownPurple = 0x11,
        PS_SkillUpRed = 0x12,
        PS_SkillDownRed = 0x13,
        PS_SkillUpOrange = 0x14,
        PS_SkillDownOrange = 0x15,
        PS_SkillUpYellow = 0x16,
        PS_SkillDownYellow = 0x17,
        PS_SkillUpGreen = 0x18,
        PS_SkillDownGreen = 0x19,
        PS_SkillUpBlue = 0x1A,
        PS_SkillDownBlue = 0x1B,
        PS_SkillUpPurple = 0x1C,
        PS_SkillDownPurple = 0x1D,
        PS_SkillDownBlack = 0x1E,
        PS_HealthUpRed = 0x1F,
        PS_HealthDownRed = 0x20,
        PS_HealthUpBlue = 0x21,
        PS_HealthDownBlue = 0x22,
        PS_HealthUpYellow = 0x23,
        PS_HealthDownYellow = 0x24,
        PS_RegenUpRed = 0x25,
        PS_RegenDownREd = 0x26,
        PS_RegenUpBlue = 0x27,
        PS_RegenDownBlue = 0x28,
        PS_RegenUpYellow = 0x29,
        PS_RegenDownYellow = 0x2A,
        PS_ShieldUpRed = 0x2B,
        PS_ShieldDownRed = 0x2C,
        PS_ShieldUpOrange = 0x2D,
        PS_ShieldDownOrange = 0x2E,
        PS_ShieldUpYellow = 0x2F,
        PS_ShieldDownYellow = 0x30,
        PS_ShieldUpGreen = 0x31,
        PS_ShieldDownGreen = 0x32,
        PS_ShieldUpBlue = 0x33,
        PS_ShieldDownBlue = 0x34,
        PS_ShieldUpPurple = 0x35,
        PS_ShieldDownPurple = 0x36,
        PS_ShieldUpGrey = 0x37,
        PS_ShieldDownGrey = 0x38,
        PS_EnchantUpRed = 0x39,
        PS_EnchantDownRed = 0x3A,
        PS_EnchantUpOrange = 0x3B,
        PS_EnchantDownOrange = 0x3C,
        PS_EnchantUpYellow = 0x3D,
        PS_EnchantDownYellow = 0x3E,
        PS_EnchantUpGreen = 0x3F,
        PS_EnchantDownGreen = 0x40,
        PS_EnchantUpBlue = 0x41,
        PS_EnchantDownBlue = 0x42,
        PS_EnchantUpPurple = 0x43,
        PS_EnchantDownPurple = 0x44,
        PS_VitaeUpWhite = 0x45,
        PS_VitaeDownBlack = 0x46,
        PS_VisionUpWhite = 0x47,
        PS_VisionDownBlack = 0x48,
        PS_SwapHealth_Red_To_Yellow = 0x49,
        PS_SwapHealth_Red_To_Blue = 0x4A,
        PS_SwapHealth_Yellow_To_Red = 0x4B,
        PS_SwapHealth_Yellow_To_Blue = 0x4C,
        PS_SwapHealth_Blue_To_Red = 0x4D,
        PS_SwapHealth_Blue_To_Yellow = 0x4E,
        PS_TransUpWhite = 0x4F,
        PS_TransDownBlack = 0x50,
        PS_Fizzle = 0x51,
        PS_PortalEntry = 0x52,
        PS_PortalExit = 0x53,
        PS_BreatheFlame = 0x54,
        PS_BreatheFrost = 0x55,
        PS_BreatheAcid = 0x56,
        PS_BreatheLightning = 0x57,
        PS_Create = 0x58,
        PS_Destroy = 0x59,
        PS_ProjectileCollision = 0x5A,
        PS_SplatterLowLeftBack = 0x5B,
        PS_SplatterLowLeftFront = 0x5C,
        PS_SplatterLowRightBack = 0x5D,
        PS_SplatterLowRightFront = 0x5E,
        PS_SplatterMidLeftBack = 0x5F,
        PS_SplatterMidLeftFront = 0x60,
        PS_SplatterMidRightBack = 0x61,
        PS_SplatterMidRightFront = 0x62,
        PS_SplatterUpLeftBack = 0x63,
        PS_SplatterUpLeftFront = 0x64,
        PS_SplatterUpRightBack = 0x65,
        PS_SplatterUpRightFront = 0x66,
        PS_SparkLowLeftBack = 0x67,
        PS_SparkLowLeftFront = 0x68,
        PS_SparkLowRightBack = 0x69,
        PS_SparkLowRightFront = 0x6A,
        PS_SparkMidLeftBack = 0x6B,
        PS_SparkMidLeftFront = 0x6C,
        PS_SparkMidRightBack = 0x6D,
        PS_SparkMidRightFront = 0x6E,
        PS_SparkUpLeftBack = 0x6F,
        PS_SparkUpLeftFront = 0x70,
        PS_SparkUpRightBack = 0x71,
        PS_SparkUpRightFront = 0x72,
        PS_PortalStorm = 0x73,
        PS_Hide = 0x74,
        PS_UnHide = 0x75,
        PS_Hidden = 0x76,
        PS_DisappearDestroy = 0x77,
        SpecialState1 = 0x78,
        SpecialState2 = 0x79,
        SpecialState3 = 0x7A,
        SpecialState4 = 0x7B,
        SpecialState5 = 0x7C,
        SpecialState6 = 0x7D,
        SpecialState7 = 0x7E,
        SpecialState8 = 0x7F,
        SpecialState9 = 0x80,
        SpecialState0 = 0x81,
        SpecialStateRed = 0x82,
        SpecialStateOrange = 0x83,
        SpecialStateYellow = 0x84,
        SpecialStateGreen = 0x85,
        SpecialStateBlue = 0x86,
        SpecialStatePurple = 0x87,
        SpecialStateWhite = 0x88,
        SpecialStateBlack = 0x89,
        PS_LevelUp = 0x8A,
        PS_EnchantUpGrey = 0x8B,
        PS_EnchantDownGrey = 0x8C,
        PS_WeddingBliss = 0x8D,
        PS_EnchantUpWhite = 0x8E,
        PS_EnchantDownWhite = 0x8F,
        PS_CampingMastery = 0x90,
        PS_CampingIneptitude = 0x91,
        PS_DispelLife = 0x92,
        PS_DispelCreature = 0x93,
        PS_DispelAll = 0x94,
        PS_BunnySmite = 0x95,
        PS_BaelZharonSmite = 0x96,
        PS_WeddingSteele = 0x97,
        PS_RestrictionEffectBlue = 0x98,
        PS_RestrictionEffectGreen = 0x99,
        PS_RestrictionEffectGold = 0x9A,
        PS_LayingofHands = 0x9B,
        PS_AugmentationUseAttribute = 0x9C,
        PS_AugmentationUseSkill = 0x9D,
        PS_AugmentationUseResistances = 0x9E,
        PS_AugmentationUseOther = 0x9F,
        PS_BlackMadness = 0xA0,
        PS_AetheriaLevelUp = 0xA1,
        PS_AetheriaSurgeDestruction = 0xA2,
        PS_AetheriaSurgeProtection = 0xA3,
        PS_AetheriaSurgeRegeneration = 0xA4,
        PS_AetheriaSurgeAffliction = 0xA5,
        PS_AetheriaSurgeFestering = 0xA6,
        PS_HealthDownVoid = 0xA7,
        PS_RegenDownVoid = 0xA8,
        PS_SkillDownVoid = 0xA9,
        PS_DirtyFightingHealDebuff = 0xAA,
        PS_DirtyFightingAttackDebuff = 0xAB,
        PS_DirtyFightingDefenseDebuff = 0xAC,
        PS_DirtyFightingDamageOverTime = 0xAD,
        NUM_PSCRIPT_TYPES = 0xAE,
        FORCE_PScriptType_32_BIT = 0x7FFFFFFF,
    };

    [Flags]
    public enum eStatFlags
    {
        none = 0,
        intStats = 1,
        boolStats = 2,
        floatStats = 4,
        stringStats = 8,
        didStats = 16,
        posStats = 32,
        iidStat = 64,
        int64Stats = 128
    }

    [Flags]
    public enum eDataFlags
    {
        none = 0,
        attributes = 1,
        skills = 2,
        body = 4,
        eventFilter = 8,
        emoteTable = 16,
        createList = 32,
        pageDataList = 64,
        generatorTable = 128,
        spellBook = 256
    }

    public enum eAttributes
    {
        none = 0,
        strength = 1,
        endurance = 2,
        quickness = 3,
        coordination = 4,
        focus = 5,
        self = 6
    }

    public enum eVitals
    {
        maxHealth = 1,
        currentHealth = 2,
        maxStamina = 3,
        currentStamina = 4,
        maxMana = 5,
        currentMana = 6
    }

    public enum eWeenieTypes
    {
        Undef = 0,
        Generic = 1,
        Clothing = 2,
        MissileLauncher = 3,
        Missile = 4,
        Ammunition = 5,
        MeleeWeapon = 6,
        Portal = 7,
        Book = 8,
        Coin = 9,
        Creature = 10,
        Admin = 11,
        Vendor = 12,
        HotSpot = 13,
        Corpse = 14,
        Cow = 15,
        AI = 16,
        Machine = 17,
        Food = 18,
        Door = 19,
        Chest = 20,
        Container = 21,
        Key = 22,
        Lockpick = 23,
        PressurePlate = 24,
        LifeStone = 25,
        Switch = 26,
        PKModifier = 27,
        Healer = 28,
        LightSource = 29,
        Allegiance = 30,
        Type32 = 31,
        SpellComponents = 32,
        ProjectileSpell = 33,
        Scroll = 34,
        Caster = 35,
        Channel = 36,
        ManaStone = 37,
        Gem = 38,
        AdvocateFane = 39,
        AdvocateItem = 40,
        Sentinel = 41,
        GSpellEconomy = 42,
        LSpellEconomy = 43,
        CraftTool = 44,
        LScoreKeeper = 45,
        GScoreKeeper = 46,
        GScoreGatherer = 47,
        ScoreBook = 48,
        EventCoordinate = 49,
        Entity = 50,
        Stackable = 51,
        HUD = 52,
        House = 53,
        Deed = 54,
        SlumLord = 55,
        Hook = 56,
        Storage = 57,
        BootSpot = 58,
        HousePortal = 59,
        Game = 60,
        GamePiece = 61,
        SkillAlterationDevice = 62,
        AttributeTransferDevice = 63,
        Hooker = 64,
        AllegianceBindstone = 65,
        InGameStatKeeper = 66,
        AugmentationDevice = 67,
        SocialManager = 68,
        Pet = 69,
        PetDevice = 70,
        CombatPet = 71
    }
}